precision mediump float;

varying vec2 vUv;

/*
Black & White Horizontal Gradient
================================
  The gradient is generated by the x coordinate of the pixel that goes from 0 to 1.
  
  (x, y) => rgb(x, x, x)

  Left side is (0, y) => rgb(0, 0, 0)
  Right side is (1, y) => rgb(1.0, 1.0, 1.0)
*/
void main() {

    float strength = vUv.x;
    gl_FragColor = vec4(vec3(strength), 1.0);
}

